### ISSUE TITLE
README is mainly talking about gocd server image

### ISSUE THREAD

**Issue by manojlds** [gocd/docker-gocd-agent#2]

**Comment by ketan** [comment]
Doh. Blame copy-pasting from https://github.com/gocd/docker-gocd-server. Do you think you can submit a PR?

**Comment by varshavaradarajan** [comment]
Hey, We have modified the readme to reflect that this repository is for the docker agent image - https://github.com/gocd/docker-gocd-agent/commit/2d17af4a4424324d43a7e82cc665b1584739059a. Thank you for reporting it.

**Comment by manojlds** [comment]
Thanks
