### ISSUE TITLE
Provide a option to write log on stdout

### ISSUE THREAD

**Issue by bdpiparva** [gocd/docker-gocd-agent#24]
* Currently log is written on file. Allow a user to provide alternate way of writing a log.

This issue is opened in favor of [Configure logging drivers](https://docs.docker.com/engine/admin/logging/overview/)

**Comment by Stono** [comment]
+1 this is very annoying, stdout is where we want our logs.
@bdpiparva : you can work around this buy building your own container FROM this image, and overriding the entrypoint with a custom script that starts the agent, and then tails the log:

```
#!/bin/bash
function stop()
{
	echo "Stopping GoCD Agent..."
	kill $gocd_pid
	kill $tail_pid
	echo "Stopped."
	exit 0
}

function start() {
	echo "Starting GoCD Agent..."
	./docker-entrypoint.sh &	
	gocd_pid=$!

	sleep 3
	tail -f /go/go-agent-bootstrapper.out.log &
	tail_pid=$!

	echo "Started (GoCD: $gocd_pid, LogTail: $tail_pid)."
}

trap stop TERM INT SIGHUP
start
wait $gocd_pid
```

Not great, but it'll do for now.

**Comment by sennerholm** [comment]
Hi!

I think that https://github.com/gocd/docker-gocd-agent/commit/2b7c7c24af0265849b36057f2535e2244d1ed46e is changing the behavior so everything should get to stdout, but I don't know when it will be released. I guess september from new version in changelog (17.9.0).

/Mikael

**Comment by ketan** [comment]
This will be released either tomorrow, or early next week.
