### ISSUE TITLE
AGENT_AUTO_REGISTER_* env vars not applied during run ?

### ISSUE THREAD

**Issue by j-ledoux** [gocd/docker-gocd-agent#28]
Hi guys,

First of all thanks for your hard work ! I'm currently testing your solution, love it !

I'm currently facing one issue through. I'm using gocd/docker-gocd-agent-alpine-3.5 and when I set environment variables AGENT_AUTO_REGISTER_HOSTNAME and AGENT_AUTO_REGISTER_RESOURCES (I'm not using the others yet) when running my agents, they still show up in GoCD server with their containers ids as agent names and they have no resources tags. I have to set tags manually every time I run an agent.

Has anyone run into the same problem ?

**Comment by varshavaradarajan** [comment]
@j-ledoux , do you also use `AGENT_AUTO_REGISTER_KEY`? The resources and hostname gets applied right after the agent is registered, I think. Let me check. Do you see the agent in the agents page showing up as pending?

**Comment by ketan** [comment]
What does `docker exec -it CONTAINER_ID cat /go/config/autoregister.properties` say? Does it contain the variables you passed in?

See [this](https://github.com/gocd/docker-gocd-agent/blob/master/docker-entrypoint.sh#L34-L37) for the reference code.

**Comment by j-ledoux** [comment]
I didn't expect to get an answer so soon ! I'm not behind my computer right now... But I'm not using the key var, but still they show up as pending in the agents tab.

**Comment by varshavaradarajan** [comment]
@j-ledoux , you need to pass along the `AGENT_AUTO_REGISTER_KEY` along with the other auto register related environment variables for them to get applied. I think the readme should put a note to that effect probably.

**Comment by j-ledoux** [comment]
Thank you @varshavaradarajan, I've just tried it out and it worked ! Indeed I didn't realize they needed the `AGENT_AUTO_REGISTER_KEY` to be applied since they showed up in the server UI.
Thanks again

**Comment by j-ledoux** [comment]
Thank you guys I totally missed that point when I read the doc. BTW if I want to set the key on the server side, I will have to insert it in the config xml on build right ? It seems that there is no env var yet.

**Comment by ketan** [comment]
Yes, you'd set it in the config xml, we autogenerate a key for you on
server startup, but you're free to change it as you need.
