### ISSUE TITLE
Need more documentation on GOCD_AGENT_DOWNLOAD_URL variable

### ISSUE THREAD

**Issue by neofob** [gocd/docker-gocd-agent#3]
What is the URL for `GOCD_AGENT_DOWNLOAD_URL`?

I try to build some gocd-agent docker image according to the `README.md`:

```
GOCD_VERSION=17.2 rake build image
rake aborted!
environment GOCD_AGENT_DOWNLOAD_URL not specified!
/home/tuan/src/docker-gocd-agent/Rakefile:21:in `get_var'
/home/tuan/src/docker-gocd-agent/Rakefile:28:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by ketan** [comment]
The download URL would be the one from  the download page, under the "zip installers" tag. The version you specified needs to be in the form X.Y.Z.

Would you like to submit a PR to the readme file?

**Comment by ketan** [comment]
I've fixed the README, so it should clarify what's needed.

**Comment by neofob** [comment]
Thanks! The commit 7fe89f86a64 fixed it! :)
