### ISSUE TITLE
Something is wrong with the latest tag

### ISSUE THREAD

**Issue by davidfrigola** [gocd/docker-gocd-agent#31]
Pulling the latest tag seems to fail:
```
docker pull gocd/gocd-agent-alpine-3.5
Using default tag: latest
Error response from daemon: manifest for gocd/gocd-agent-alpine-3.5:latest not found
```

But works flawlessly for v17.4.0 and v.17.3.0

```
docker pull gocd/gocd-agent-alpine-3.5:v17.3.0
v17.3.0: Pulling from gocd/gocd-agent-alpine-3.5
627beaf3eaaf: Already exists
ba50dc5e812e: Pull complete
47daa26e069d: Pull complete
7351f6eed267: Pull complete
8a65fa6c9068: Pull complete
00fb8ace5846: Pull complete
Digest: sha256:dd2a7c67d0cf1688ad37476a0d77ea4f7f265c874a6b0c319eea22db74fca158
Status: Downloaded newer image for gocd/gocd-agent-alpine-3.5:v17.3.0
```

Not a big deal though

**Comment by varshavaradarajan** [comment]
https://github.com/gocd/docker-gocd-agent/issues/10

**Comment by varshavaradarajan** [comment]
You might want to checkout https://github.com/gocd/docker-gocd-agent/issues/10#issuecomment-294933192

**Comment by davidfrigola** [comment]
Thanks, just realised the `note` in the instructions.
I was just using the `Docker pull command` in the top right of https://hub.docker.com/r/gocd/gocd-agent-alpine-3.5/ , which confused me, and might confuse others.

**Comment by varshavaradarajan** [comment]
Yeah, that's a problem. Its dockerhub that does it though, when we create the repository. There is no way, we can get rid of it when we create a dockerhub repository.
