### ISSUE TITLE
Can't get the the gocd-agent to connect to the server with Docker compose

### ISSUE THREAD

**Issue by bradmunz79** [gocd/docker-gocd-agent#50]
Below is a simple docker compose file to setup a go server and agent. The agent refuses to connect to the agent. I can confirm that the gocd-server host address is reachable from the agent.

```
version: '3'
services:
  go-server:
    networks:
        - service-net
    image: "gocd/gocd-server:v17.11.0"  
    ports:    
        - "8153:8153"
        - "8154:8154"                    
  go-agent: 
    networks:
        - service-net
    image: "gocd/gocd-agent-ubuntu-16.04:v17.11.0"
    depends_on:
        - go-server      
    environment:
        GO_SERVER_URL: "https://go-server:8514/go"        
networks:
    service-net:
```

It seems the server is rejecting the connection:

go-agent_1   | 2017-11-09 14:33:16,260 ERROR [main] ServerBinaryDownloader:80 - Couldn't update admin/agent-launcher.jar. Sleeping for 1m. Error:
go-agent_1   | org.apache.http.conn.HttpHostConnectException: Connect to go-server:8514 [go-server/172.20.0.2] failed: Connection refused (Connection refused)
go-agent_1   |  at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
go-agent_1   |  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
go-agent_1   |  at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
go-agent_1   |  at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
go-agent_1   |  at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
go-agent_1   |  at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
go-agent_1   |  at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
go-agent_1   |  at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
go-agent_1   |  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
go-agent_1   |  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
go-agent_1   |  at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.fetchUpdateCheckHeaders(ServerBinaryDownloader.java:96)
go-agent_1   |  at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:72)
go-agent_1   |  at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.doLaunch(AgentLauncherImpl.java:90)
go-agent_1   |  at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.lambda$launch$0(AgentLauncherImpl.java:68)
go-agent_1   |  at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:62)
go-agent_1   |  at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:68)
go-agent_1   |  at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:79)
go-agent_1   |  at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.lambda$main$0(AgentBootstrapper.java:60)
go-agent_1   |  at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:53)
go-agent_1   |  at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:60)
go-agent_1   |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
go-agent_1   |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
go-agent_1   |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
go-agent_1   |  at java.lang.reflect.Method.invoke(Method.java:498)
go-agent_1   |  at com.thoughtworks.gocd.Boot.run(Boot.java:104)
go-agent_1   |  at com.thoughtworks.gocd.Boot.main(Boot.java:55)
go-agent_1   | Caused by: java.net.ConnectException: Connection refused (Connection refused)
go-agent_1   |  at java.net.PlainSocketImpl.socketConnect(Native Method)
go-agent_1   |  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
go-agent_1   |  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
go-agent_1   |  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
go-agent_1   |  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
go-agent_1   |  at java.net.Socket.connect(Socket.java:589)
go-agent_1   |  at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
go-agent_1   |  at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
go-agent_1   |  ... 25 common frames omitted

**Comment by arvindsv** [comment]
There's a typo in this line:

```
GO_SERVER_URL: "https://go-server:8514/go"  
```

It should be 8154.
