### ISSUE TITLE
agent binaries url not reachable

### ISSUE THREAD

**Issue by pushthat** [gocd/docker-gocd-agent#78]
Hello,

The url https://download.gocd.org/experimental/binaries/18.9.0-7478/generic/go-agent-18.9.0-7478.zip return code 404.
It is a problem for this Dockerfile for example https://github.com/gocd/docker-gocd-agent-ubuntu-16.04/blob/master/Dockerfile.

Regard,

**Comment by GaneshSPatil** [comment]
@pushthat -- Thanks for reporting the issue. 
The dockerfiles of all the GoCD images for tag `v18.9.0` has been updated to fix the agent binary url.

I am closing this issue marking as fixed.

**Comment by pushthat** [comment]
Thanks !
