### ISSUE TITLE
The gocd-agent-docker-dind image doc has a little mistake

### ISSUE THREAD

**Issue by FaustYKKN** [gocd/docker-gocd-agent#80]
The demo commond in [docs of gocd-agent-docker-dind](https://hub.docker.com/r/gocd/gocd-agent-docker-dind/)
`docker run -itd -e GO_SERVER_URL=https://$(docker inspect --format='{{(index (index .NetworkSettings.IPAddress))}}' angry_feynman):8154/go gocd/gocd-agent-docker-dind:v18.10.0`,
without `--privileged` flag, make the agent container cannot start the docker daemon.

**Comment by arvindsv** [comment]
Thank you, @FaustYKKN. Fixed in https://github.com/gocd/gocd-agent-docker-dind/pull/3
